version: "3"
services:
  api:
    hostname: api
    build: ./app/
    image: event-planner-api:latest
    ports:
    - "8080:8080"
    env_file:
    - app/.env
    volumes:
      - ./app:/app
    command: python api.py

  web:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - gui

  rabbitmq:
    image: rabbitmq:3.13.1-management-alpine
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672

  postgres:
    image: postgres:13.3-alpine
    hostname: db
    environment:
      POSTGRES_DB: local_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
        - 5432:5432

  worker:
    build: ./app/
    image: event-planner-api:latest
    env_file:
      - app/.env
    volumes:
      - ./app:/app
    command: python services/ml/rm_predict_worker.py
    depends_on:
      rabbitmq:
        condition: service_started
    restart: on-failure

  gui:
    build: ./app/
    image: event-planner-api:latest
    env_file:
      - app/.env
    volumes:
      - ./app:/app
    #command: streamlit run gui/streamlit_app.py
    depends_on:
      worker:
        condition: service_started
    expose:
      - 8501
    #ports:
    #  - 8501:8501
    entrypoint: ["streamlit", "run", "gui/streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]